export const drinkList = [
  "Seagram's 7",
  "7-Up",
  "Vodka",
  "Gin",
  "Rum",
  "Blue Curacao",
  "Sour Mix",
  "Sloe Gin",
  "Southern Comfort",
  "Amaretto",
  "Orange Juice",
  "Sour Apple Pucker",
  "Lime Juice",
  "Apple Pucker",
  "Goldschlager",
  "Pineapple Juice",
  "Kahlua",
  "Bailey's",
  "Grand Marnier",
  "Cranberry Juice",
  "Bloody Mary Mix",
  "Tabasco or Worcestershire",
  "Whipped cream",
  "Tequila",
  "Blue Caracao",
  "Whiskey",
  "Peach Schnapps",
  "Grenadine",
  "Butterscotch Schnapps",
  "Orange Vodka ",
  "Cuervo 1800",
  "Stoli Vanilla",
  "Frangelico",
  "Creme de Cacao",
  "Cream",
  "Kahula",
  "Coke",
  "Triple Sec",
  "Gin or Vodka",
  "Dry Vermouth",
  "Olive Juice",
  "Bacardi 151",
  "Cognac",
  "Grapefruit Juice",
  "Myer's Dark Rum",
  "Pineapple",
  "Hpnotiq",
  "Bailey's ",
  "Jameson",
  "Jagermeister",
  "Citrus Vodka",
  "Lemon Juice",
  "Jack Daniel's",
  "Sprite",
  "Whisky",
  "Sweet Vermouth",
  "Watermelon Pucker",
  "Midori",
  "Soda Water",
  "Chambord",
  "Lime juice",
  "Grapefruit Juice ",
  "Malibu Rum",
  "Whipped Cream",
  "Jagermerister",
  "Johnny Walker",
  "Jim Beam",
  "Crown Apple",
  "White Cacao",
  "Stoli Razberi",
];
